version: '3'
services:

  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - pg
    ports:
      - "9091:9000"
    restart: unless-stopped
    tty: true    
    networks:
      - app-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg:5432/sonarqube
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  pg:
    image: postgres
    ports:
        - "5432:5432"
    restart: unless-stopped
    tty: true    
    networks:
      - app-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  sonarqube_conf: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_bundled-plugins: {}
  postgresql: {}
  postgresql_data: {}