version: '3'
services:
 
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: db

      ports:
          - "8081:80"
      restart: always
      volumes:
          - ./php/local.ini:/usr/local/etc/php/php.ini
      networks:
        - app-network             
  
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  